Repository WildCodeSchool/orleans-0918-php-wastity, pull requests merged in 2018-12, with the labels that each got.

#66 S2 us2
  src/Controller/FoodHeroController.php
  src/Controller/ProfileController.php
  src/Entity/FoodHero.php
  src/Entity/User.php
  src/Form/FoodHeroType.php
  src/Migrations/Version20181130082906.php
  templates/defineProfile.html.twig
Labels: Corrections Done, Reviewed By PO

#70 Fix global
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/login.html.twig
Labels: Reviewed By PO

#73 migration propre
  src/Migrations/Version20181121135910.php
  src/Migrations/Version20181122090304.php
  src/Migrations/Version20181122130310.php
  src/Migrations/Version20181126102901.php
  src/Migrations/Version20181127100958.php
  src/Migrations/Version20181128141741.php
  src/Migrations/Version20181128151121.php
  src/Migrations/Version20181130082906.php
  src/Migrations/Version20181130093429.php
  src/Migrations/Version20181203124904.php
Labels: Reviewed By PO

#71 Suppression des médias queries
  assets/css/appProfile.scss
Labels: Reviewed By PO

#68 Us 54 navigation admin
  assets/css/appAdmin.scss
  src/Controller/AdminAssociationController.php
  src/Controller/AdminCompanyController.php
  src/Controller/AdminController.php
  src/Controller/AdminFoodHeroController.php
  src/Controller/AdminOfferController.php
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  templates/Admin/associationIndex.html.twig
  templates/Admin/companyIndex.html.twig
  templates/Admin/foodHeroIndex.html.twig
  templates/Admin/index.html.twig
  templates/Admin/layoutAdmin.html.twig
  templates/Admin/offerIndex.html.twig
  webpack.config.js
Labels: Reviewed By PO

#75 S3 us38 offers association
  src/Controller/OfferController.php
  src/Repository/OfferRepository.php
  templates/Visitor/Offer/index.html.twig
Labels: Reviewed By PO

#85 Dev
  .env.dist
  .gitignore
  assets/css/app.scss
  assets/css/appAdmin.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  src/Controller/AdminAssociationController.php
  src/Controller/AdminCompanyController.php
  src/Controller/AdminController.php
  src/Controller/AdminFoodHeroController.php
  src/Controller/AdminOfferController.php
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/Controller/ProfileController.php
  src/Entity/Company.php
  src/Entity/DaysOfWeek.php
  src/Entity/FoodHero.php
  src/Entity/Schedule.php
  src/Entity/User.php
  src/Form/CompanyScheduleType.php
  src/Form/FoodHeroType.php
  src/Form/ScheduleType.php
  src/Migrations/Version20181121135910.php
  src/Migrations/Version20181122090304.php
  src/Migrations/Version20181122130310.php
  src/Migrations/Version20181126102901.php
  src/Migrations/Version20181127100958.php
  src/Migrations/Version20181128151121.php
  src/Migrations/Version20181203124904.php
  src/Migrations/Version20181204100334.php
  src/Repository/DaysOfWeekRepository.php
  src/Repository/OfferRepository.php
  src/Repository/ScheduleRepository.php
  templates/Admin/associationIndex.html.twig
  templates/Admin/companyIndex.html.twig
  templates/Admin/foodHeroIndex.html.twig
  templates/Admin/index.html.twig
  templates/Admin/layoutAdmin.html.twig
  templates/Admin/offerIndex.html.twig
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Company/_formSchedule.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/Visitor/Offer/index.html.twig
  templates/base.html.twig
  templates/defineProfile.html.twig
  templates/login.html.twig
  webpack.config.js
Labels: Reviewed By PO

#87 Us50 schedule association
  src/Controller/AssociationController.php
  src/Entity/Association.php
  src/Entity/Schedule.php
  src/Form/AssociationScheduleType.php
  src/Migrations/Version20181204151328.php
  templates/Visitor/Association/_formSchedule.html.twig
  templates/Visitor/Association/editSchedule.html.twig
  templates/Visitor/Association/show.html.twig
Labels: Reviewed By PO

#77 visuel associationIndex
  templates/Admin/associationIndex.html.twig
Labels: Corrections Done, Reviewed By PO

#79 Visuel liste des Foodheroes
  templates/Admin/foodHeroIndex.html.twig
Labels: Corrections Done, Reviewed By PO

#88 ajout d'une photo de profil food hero
  .gitignore
  assets/css/app.scss
  assets/css/appFoodHero.scss
  assets/css/projectVar.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  src/Entity/FoodHero.php
  src/Form/FoodHeroType.php
  src/Migrations/Version20181205105050.php
  src/Migrations/Version20181205110613.php
  symfony.lock
  templates/Visitor/FoodHero/_form.html.twig
Labels: Corrections Done, Reviewed By PO

#89 Us 61 show company
  assets/css/appCompany.scss
  src/Controller/CompanyController.php
  src/Entity/Company.php
  templates/Visitor/Company/show.html.twig
Labels: Reviewed By PO

#92 Us 62 show association
  assets/css/appAssociation.scss
  src/Controller/AssociationController.php
  src/Entity/Association.php
  templates/Visitor/Association/show.html.twig
Labels: Reviewed By PO

#72 Us16 visualisation et modification offre entreprise
  .env
  assets/css/app.scss
  assets/css/appCompany.scss
  src/Controller/CompanyController.php
  src/Controller/OfferController.php
  src/Entity/Company.php
  src/Entity/Offer.php
  src/Entity/User.php
  src/Migrations/Version20181203093818.php
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/Offer/index.html.twig
  templates/Visitor/Offer/show.html.twig
  templates/base.html.twig
  templates/login.html.twig
Labels: Corrections Done, Reviewed By PO

#91 Routes refaites et navbar reparé
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  assets/css/projectVar.scss
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  templates/Visitor/Association/_form.html.twig
  templates/Visitor/Association/edit.html.twig
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/FoodHero/navBarFoodHero.html.twig
Labels: Corrections Done

#94 page édition du foodhero
  assets/css/appFoodHero.scss
  config/packages/vich_uploader.yaml
  src/Controller/FoodHeroController.php
  src/Form/FoodHeroType.php
  templates/Visitor/FoodHero/edit.html.twig
Labels: Corrections Done, Reviewed By PO

#95 correction
  src/Entity/Offer.php
  src/Migrations/Version20181207124815.php
Labels: Reviewed By PO

#98 ajout des id dans les routes company ey association
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  templates/Admin/companyIndex.html.twig
  templates/Admin/offerIndex.html.twig
Labels: Reviewed By PO

#101 S4 us26 foodhero list offer
  assets/css/appFoodHero.scss
  src/Controller/FoodHeroController.php
  src/Entity/FoodHero.php
  src/Entity/Offer.php
  src/Migrations/Version20181210162814.php
  src/Repository/OfferRepository.php
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/navBarFoodHero.html.twig
  templates/defineProfile.html.twig
Labels: Reviewed By PO

#100 Us 63 offers images
  assets/css/appCompany.scss
  config/packages/vich_uploader.yaml
  src/Entity/Offer.php
  src/Form/OfferType.php
  src/Migrations/Version20181203124904.php
  src/Migrations/Version20181210165622.php
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Offer/_form.html.twig
Labels: Conflics, Corrections Done, question

#104 DevToMaster
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  config/packages/vich_uploader.yaml
  src/Controller/FoodHeroController.php
  src/Entity/FoodHero.php
  src/Entity/Offer.php
  src/Form/OfferType.php
  src/Migrations/Version20181203124904.php
  src/Migrations/Version20181210162814.php
  src/Migrations/Version20181210165622.php
  src/Repository/OfferRepository.php
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/navBarFoodHero.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/defineProfile.html.twig
Labels: Reviewed By PO

#102 Us41 distance assoc company
  composer.json
  composer.lock
  src/Controller/AssociationController.php
  src/Controller/HasAddress.php
  src/Controller/OfferController.php
  src/Entity/Association.php
  src/Entity/Company.php
  src/Service/DistanceCalculator.php
  symfony.lock
  templates/Visitor/Association/layoutAssociation.html.twig
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#108 small fixes on navbar
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/FoodHero/navBarFoodHero.html.twig
Labels: Corrections Done, Reviewed By PO

#110 Fix foodhero edit image
  src/Controller/FoodHeroController.php
  src/Entity/FoodHero.php
  src/Entity/Offer.php
  src/Form/FoodHeroType.php
Labels: Reviewed By PO

#105 SPRINT #04 US-64 Status de l'offre "en recherche d'association"
  assets/css/appCompany.scss
  templates/Visitor/Company/listOffers.html.twig
Labels: Reviewed By PO

#106 S4 us27 fh select offer
  src/Controller/AssociationController.php
  src/Controller/FoodHeroController.php
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#107 US_MiseAJoursFixture
  src/DataFixtures/AssociationFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/DayOfWeekFixtures.php
  src/DataFixtures/FoodHeroFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/ScheduleFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Offer.php
Labels: Reviewed By PO

#112 corrections orthographe
  templates/Admin/associationIndex.html.twig
  templates/Admin/companyShow.html.twig
Labels: Reviewed By PO

#113 fix des fixtures et ortho
  src/DataFixtures/UserFixtures.php
  src/Entity/Association.php
  templates/Admin/associationShow.html.twig
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/show.html.twig
Labels: Reviewed By PO

#111 ajout des messages en français
  config/services.yaml
  src/Security/LoginAuthenticator.php
Labels: Corrections Done, Reviewed By PO

#114 Fix dev fixtures user
  assets/css/app.scss
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/DataFixtures/ScheduleFixtures.php
  src/Form/OfferType.php
  templates/Visitor/Association/edit.html.twig
  templates/Visitor/Association/editSchedule.html.twig
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/new.html.twig
  templates/defineProfile.html.twig
Labels: Reviewed By PO

#116 DevToMaster
  assets/css/app.scss
  assets/css/appCompany.scss
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/HasAddress.php
  src/Controller/OfferController.php
  src/DataFixtures/AssociationFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/DayOfWeekFixtures.php
  src/DataFixtures/FoodHeroFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/ScheduleFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Association.php
  src/Entity/Company.php
  src/Entity/FoodHero.php
  src/Entity/Offer.php
  src/Form/AssociationType.php
  src/Form/FoodHeroType.php
  src/Form/OfferType.php
  src/Migrations/Version20181203124904.php
  src/Security/LoginAuthenticator.php
  src/Service/DistanceCalculator.php
  symfony.lock
  templates/Admin/associationIndex.html.twig
  templates/Admin/associationShow.html.twig
  templates/Admin/companyShow.html.twig
  templates/Visitor/Association/edit.html.twig
  templates/Visitor/Association/editSchedule.html.twig
  templates/Visitor/Association/layoutAssociation.html.twig
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/navBarFoodHero.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/new.html.twig
  templates/defineProfile.html.twig
Labels: Reviewed By PO

#117 Fix listing offres entreprise
  templates/Visitor/Company/listOffers.html.twig
Labels: Reviewed By PO

#120 Fix card association
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  assets/images/wastityPlaceHolder.png
  src/Controller/AssociationController.php
  src/DataFixtures/OfferFixtures.php
  src/Security/LoginAuthenticator.php
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#121 Sprint04 us65_Statut Offre
  src/Controller/AssociationController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Offer.php
  src/Entity/Status.php
  src/Migrations/Version20181217104813.php
  src/Repository/StatusRepository.php
  templates/Visitor/Company/listOffers.html.twig
Labels: Corrections Done, Reviewed By PO

#123 S5_US53_security company list offers
  src/Controller/CompanyController.php
  src/Security/Voter/CompanyVoter.php
Labels: Corrections Done, Reviewed By PO

#128 Dev to master
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  assets/images/wastityPlaceHolder.png
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Offer.php
  src/Entity/Status.php
  src/Migrations/Version20181217104813.php
  src/Repository/OfferRepository.php
  src/Repository/StatusRepository.php
  src/Security/LoginAuthenticator.php
  src/Security/Voter/CompanyVoter.php
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/navBarFoodHero.html.twig
Labels: Reviewed By PO

#124 S5_US70_Security Access Company offers
  src/Controller/OfferController.php
  src/Security/Voter/OfferVoter.php
Labels: Reviewed By PO

#126 Sprint05 us43 Page Historique Association
  src/Controller/AssociationController.php
  src/Repository/OfferRepository.php
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/record.html.twig
Labels: Corrections Done, Reviewed By PO

#127 SPRINT05-US20 Création page historique entreprise
  src/Controller/CompanyController.php
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/Company/record.html.twig
Labels: Corrections Done, Reviewed By PO

#130 fix card entreprises
  assets/css/app.scss
  src/Controller/CompanyController.php
  src/DataFixtures/OfferFixtures.php
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/showCard.html.twig
Labels: Reviewed By PO

#135 mise à jour des cartes
  assets/css/app.scss
  assets/css/appFoodHero.scss
  src/Controller/FoodHeroController.php
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Reviewed By PO

#131 Correction des routes
  src/Controller/CompanyController.php
  src/Controller/OfferController.php
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Offer/edit.html.twig
Labels: Corrections Done, Reviewed By PO

#136 Correction de petite erreur du bouton modifier
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/showCard.html.twig
Labels: Reviewed By PO

#132 Us80 page statistique entreprise
  src/Controller/CompanyController.php
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/Company/showStatistics.html.twig
Labels: Corrections Done
