Repository WildCodeSchool/orleans-0918-php-wastity, pull requests merged in 2019-01, with the labels that each got.

#148 S79_add security on Company records, showCompany and Company statistic
  src/Controller/CompanyController.php
Labels: Reviewed By PO

#149 S83_add security access on showasso and record
  src/Controller/AssociationController.php
  src/Security/Voter/AssociationVoter.php
Labels: Reviewed By PO

#139 ajout des offres dans l'admin
  src/Controller/AdminOfferController.php
  src/Entity/Offer.php
  src/Entity/User.php
  templates/Admin/offerIndex.html.twig
Labels: Corrections Done, Reviewed By PO

#151 Fixture Admin
  src/DataFixtures/UserFixtures.php
Labels: Reviewed By PO

#150 Dev -> Master
  assets/css/app.scss
  assets/css/appFoodHero.scss
  src/Controller/AdminOfferController.php
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/DataFixtures/FoodHeroFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Offer.php
  src/Entity/User.php
  src/Repository/OfferRepository.php
  src/Security/Voter/AssociationVoter.php
  src/Security/Voter/OfferVoter.php
  templates/Admin/offerIndex.html.twig
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
  templates/Visitor/Offer/edit.html.twig
Labels: Reviewed By PO

#118 fixe mise en page section entreprise
  assets/css/appCompany.scss
  assets/css/projectVar.scss
  assets/images/logo-wastity_blanc.png
  package.json
  src/Controller/OfferController.php
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/headerCompany.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/new.html.twig
  yarn.lock
Labels: Corrections Done, Reviewed By PO

#146 Us 94 detail offre admin
  src/Controller/AdminOfferController.php
  templates/Admin/offerIndex.html.twig
  templates/Admin/offerShow.html.twig
Labels: Reviewed By PO

#137 collecte des offres par un food hero
  assets/css/appFoodHero.scss
  src/Controller/FoodHeroController.php
  src/Repository/OfferRepository.php
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
Labels: Corrections Done, Reviewed By PO

#133 geolocalisation FH
  src/Controller/AssociationController.php
  src/Controller/FoodHeroController.php
  src/Controller/SecurityController.php
  src/DataFixtures/CompanyFixtures.php
  src/Service/DistanceCalculator.php
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/show.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#152 S73_securityFH
  src/Controller/FoodHeroController.php
  src/Security/Voter/FoodheroVoter.php
  templates/Visitor/FoodHero/_delete_form.html.twig
  templates/Visitor/FoodHero/show.html.twig
Labels: Reviewed By PO

#153 Fixe section food hero
  assets/css/appFoodHero.scss
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/headerFoodHero.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#155 Page statistique association
  src/Controller/AssociationController.php
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Association/showStatistics.html.twig
Labels: Reviewed By PO

#147 Us 93 activate offer
  assets/css/app.scss
  src/Controller/AdminOfferController.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/Offer.php
  src/Repository/OfferRepository.php
  templates/Admin/index.html.twig
  templates/Admin/offerIndex.html.twig
  templates/Admin/offerShow.html.twig
Labels: Corrections Done, Reviewed By PO

#158 Fix dev v2
  assets/css/appFoodHero.scss
  src/Controller/AssociationController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/Entity/Company.php
  src/Entity/Offer.php
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Company/_formSchedule.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/headerFoodHero.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Reviewed By PO

#157 Fix Page stat company et asso
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  templates/Visitor/Association/showStatistics.html.twig
  templates/Visitor/Company/showStatistics.html.twig
Labels: Reviewed By PO

#160 Ajout message flash
  assets/css/app.scss
  src/Controller/AdminOfferController.php
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/Controller/SecurityController.php
  templates/base.html.twig
Labels: Reviewed By PO

#161 modal enlevée plus helpers
  assets/css/app.scss
  assets/css/projectVar.scss
  src/Form/OfferType.php
  templates/Visitor/Offer/_form.html.twig
Labels: Reviewed By PO

#163 ajout de l'active sur les navbars
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  templates/Visitor/Association/navbarAssociation.html.twig
  templates/Visitor/Company/navbarCompany.html.twig
  templates/Visitor/FoodHero/navBarFoodHero.html.twig
Labels: Reviewed By PO

#167 ajout image et nom foodhero admin
  templates/Admin/foodHeroIndex.html.twig
Labels: Reviewed By PO

#165 Fix style
  assets/css/appFoodHero.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  assets/images/company.png
  assets/images/heart.png
  assets/images/super(3).png
  templates/defineProfile.html.twig
Labels: Corrections Done, Reviewed By PO

#168 vue des users dans l'admin
  src/Controller/AdminUserController.php
  src/Controller/SecurityController.php
  templates/Admin/index.html.twig
  templates/Admin/userIndex.html.twig
Labels: Reviewed By PO

#162 Us8 company member
  src/Controller/CompanyController.php
  src/Entity/Company.php
  src/Entity/User.php
  src/Form/CompanyMemberType.php
  src/Migrations/Version20190107085906.php
  src/Security/Voter/CompanyVoter.php
  templates/Visitor/Company/_deleteMember_form.html.twig
  templates/Visitor/Company/_formMember.html.twig
  templates/Visitor/Company/show.html.twig
  templates/base.html.twig
Labels: Corrections Done, Reviewed By PO

#171 Pagination company
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  config/packages/knp_paginator.yaml
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Company/listOffers.html.twig
  translations/KnpPaginatorBundle.yml
Labels: Corrections Done, Reviewed By PO

#159 Redirect page admin
  src/Security/LoginAuthenticator.php
Labels: Changes Requested

#174 geoloc
  assets/js/geolocation.js
  src/Controller/AssociationController.php
  src/Controller/FoodHeroController.php
  templates/Visitor/Association/new.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  webpack.config.js
Labels: Reviewed By PO

#172 Asso add member
  src/Controller/AssociationController.php
  src/Entity/Association.php
  src/Entity/User.php
  src/Form/AssociationMemberType.php
  src/Migrations/Version20190108092112.php
  templates/Visitor/Association/_formMember.html.twig
  templates/Visitor/Association/show.html.twig
Labels: Corrections Done, Reviewed By PO

#173 Asso remove member
  src/Controller/AssociationController.php
  templates/Visitor/Association/_deleteMember_form.html.twig
  templates/Visitor/Association/show.html.twig
Labels: Corrections Done, Reviewed By PO

#178 Pagination admin
  config/packages/paginator.yaml
  src/Controller/AdminAssociationController.php
  src/Controller/AdminCompanyController.php
  src/Controller/AdminFoodHeroController.php
  src/Controller/AdminOfferController.php
  templates/Admin/associationIndex.html.twig
  templates/Admin/companyIndex.html.twig
  templates/Admin/foodHeroIndex.html.twig
  templates/Admin/offerIndex.html.twig
  translations/KnpPaginatorBundle.yml
Labels: Corrections Done, Reviewed By PO

#179 page d'erreur 403 et 404
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: question

#182 Pagination des tableaux
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/FoodHero/record.html.twig
Labels: Reviewed By PO

#183 Pagination Admin Users
  src/Controller/AdminUserController.php
  templates/Admin/userIndex.html.twig
Labels: Reviewed By PO

#170 Page modif asso et entreprise
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  templates/Visitor/Association/_formSchedule.html.twig
  templates/Visitor/Association/edit.html.twig
  templates/Visitor/Association/editSchedule.html.twig
  templates/Visitor/Association/headerAssociation.html.twig
  templates/Visitor/Association/layoutAssociation.html.twig
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Association/showStatistics.html.twig
  templates/Visitor/Company/_formSchedule.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/headerCompany.html.twig
  templates/Visitor/Company/layoutCompany.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/headerFoodHero.html.twig
  templates/Visitor/FoodHero/layoutFoodHero.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/new.html.twig
  templates/headerLogo.html.twig
Labels: Corrections Done, Reviewed By PO

#181 readme
  README.md
Labels: Reviewed By PO

#175 Page Food Hero
  assets/css/appFoodHero.scss
  src/Controller/FoodHeroController.php
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
Labels: Corrections Done, Reviewed By PO

#187 geo bug
  assets/js/geolocation.js
Labels: Reviewed By PO

#176 Fix cards
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  assets/css/appProfile.scss
  assets/images/company.png
  assets/images/heart.png
  src/Controller/AssociationController.php
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
  templates/defineProfile.html.twig
Labels: Corrections Done, Reviewed By PO

#190 Activation user
  src/Controller/AdminUserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Security/LoginAuthenticator.php
  templates/Admin/userIndex.html.twig
Labels: Reviewed By PO

#185 securityMemberCompany
  src/Controller/CompanyController.php
  src/Security/Voter/CompanyVoter.php
  templates/Visitor/Company/show.html.twig
Labels: Reviewed By PO

#189 taille message flash et titre
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  assets/css/projectVar.scss
  templates/Visitor/Association/edit.html.twig
  templates/Visitor/Association/editSchedule.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showStatistics.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/index.html.twig
  templates/Visitor/Offer/new.html.twig
  templates/defineProfile.html.twig
Labels: Corrections Done, Reviewed By PO

#191 Redirection Page Admin -> Page Profile
  templates/Admin/index.html.twig
Labels: Reviewed By PO

#192 securityMemberAssociation
  src/Controller/AssociationController.php
  src/Security/Voter/AssociationVoter.php
  templates/Visitor/Association/_deleteMember_form.html.twig
  templates/Visitor/Association/show.html.twig
Labels: Reviewed By PO

#193 Couleur changée
  src/DataFixtures/StatusFixtures.php
Labels: Reviewed By PO

#194 Padding
  templates/Visitor/Association/showStatistics.html.twig
  templates/Visitor/Company/showStatistics.html.twig
Labels: Reviewed By PO

#195 Couleur Boutton User et offre activer / desactiver
  templates/Admin/offerShow.html.twig
  templates/Admin/userIndex.html.twig
Labels: Reviewed By PO

#199 Fix card foodhero
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  assets/css/appProfile.scss
  src/Controller/FoodHeroController.php
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showDistanceOffer.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#200 dropdown choice for company section
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  src/Entity/User.php
  templates/Visitor/Company/dropdownCompanyChoice.html.twig
  templates/Visitor/Company/layoutCompany.html.twig
Labels: Corrections Done, Reviewed By PO

#201 fix set activate
  src/Controller/SecurityController.php
Labels: Reviewed By PO

#204 Dev
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  src/Controller/AdminUserController.php
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/SecurityController.php
  src/DataFixtures/StatusFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Security/LoginAuthenticator.php
  src/Security/Voter/AssociationVoter.php
  src/Security/Voter/CompanyVoter.php
  templates/Admin/index.html.twig
  templates/Admin/offerShow.html.twig
  templates/Admin/userIndex.html.twig
  templates/Visitor/Association/_deleteMember_form.html.twig
  templates/Visitor/Association/dropdownAssociationChoice.html.twig
  templates/Visitor/Association/edit.html.twig
  templates/Visitor/Association/editSchedule.html.twig
  templates/Visitor/Association/layoutAssociation.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Association/showOffer.html.twig
  templates/Visitor/Association/showStatistics.html.twig
  templates/Visitor/Company/dropdownCompanyChoice.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/layoutCompany.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showCard.html.twig
  templates/Visitor/FoodHero/showDistanceOffer.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/index.html.twig
  templates/Visitor/Offer/new.html.twig
  templates/defineProfile.html.twig
Labels: Reviewed By PO

#205 migration
  src/Migrations/Version20181203124904.php
  src/Migrations/Version20181204100334.php
  src/Migrations/Version20181204151328.php
  src/Migrations/Version20181205090735.php
  src/Migrations/Version20181205105050.php
  src/Migrations/Version20181205110613.php
  src/Migrations/Version20181205145714.php
  src/Migrations/Version20181207124815.php
  src/Migrations/Version20181210162814.php
  src/Migrations/Version20181210165622.php
  src/Migrations/Version20181217104813.php
  src/Migrations/Version20190107085906.php
  src/Migrations/Version20190108092112.php
  src/Migrations/Version20190110131313.php
Labels: Corrections Done, Reviewed By PO

#207 Dev
  src/Controller/AdminUserController.php
  src/Migrations/Version20181203124904.php
  src/Migrations/Version20181204100334.php
  src/Migrations/Version20181204151328.php
  src/Migrations/Version20181205090735.php
  src/Migrations/Version20181205105050.php
  src/Migrations/Version20181205110613.php
  src/Migrations/Version20181205145714.php
  src/Migrations/Version20181207124815.php
  src/Migrations/Version20181210162814.php
  src/Migrations/Version20181210165622.php
  src/Migrations/Version20181217104813.php
  src/Migrations/Version20190107085906.php
  src/Migrations/Version20190108092112.php
  src/Migrations/Version20190110131313.php
Labels: Reviewed By PO

#208 apache
  composer.json
  composer.lock
  public/.htaccess
  symfony.lock
Labels: Reviewed By PO

#214 Dev
  composer.json
  composer.lock
  public/.htaccess
  symfony.lock
Labels: Reviewed By PO

#212 Fix fh
  assets/css/appFoodHero.scss
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Reviewed By PO

#202 Possibilité de quitter une entreprise et une association
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Security/Voter/CompanyVoter.php
  templates/Visitor/Association/_leaveAssociation_form.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Company/_leaveCompany_form.html.twig
  templates/Visitor/Company/show.html.twig
Labels: Corrections Done, Reviewed By PO

#209 Fix choice asso
  templates/Visitor/Association/dropdownAssociationChoice.html.twig
Labels: Reviewed By PO

#211 ajout des alt des images
  templates/Admin/index.html.twig
  templates/headerLogo.html.twig
  templates/login.html.twig
  templates/register.html.twig
Labels: Reviewed By PO

#206 modif du bouton voir plus voir moins des cards
  assets/css/app.scss
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
  templates/base.html.twig
Labels: Corrections Done

#213 Fix style profile et company
  assets/css/app.scss
  assets/css/appCompany.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  src/Controller/CompanyController.php
  src/Entity/Company.php
  templates/Visitor/Company/_deleteMember_form.html.twig
  templates/Visitor/Company/_formMember.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/defineProfile.html.twig
  templates/headerLogo.html.twig
Labels: Corrections Done

#216 Dev
  assets/css/app.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  assets/css/appProfile.scss
  assets/css/projectVar.scss
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Entity/Company.php
  src/Repository/OfferRepository.php
  src/Security/Voter/CompanyVoter.php
  templates/Admin/index.html.twig
  templates/Visitor/Association/_leaveAssociation_form.html.twig
  templates/Visitor/Association/dropdownAssociationChoice.html.twig
  templates/Visitor/Association/edit.html.twig
  templates/Visitor/Association/editSchedule.html.twig
  templates/Visitor/Association/listOffers.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Association/showStatistics.html.twig
  templates/Visitor/Company/_deleteMember_form.html.twig
  templates/Visitor/Company/_formMember.html.twig
  templates/Visitor/Company/_leaveCompany_form.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
  templates/base.html.twig
  templates/defineProfile.html.twig
  templates/headerLogo.html.twig
  templates/login.html.twig
  templates/register.html.twig
Labels: Reviewed By PO

#219 Fix modif header
  assets/css/appAssociation.scss
  assets/css/appFoodHero.scss
Labels: Reviewed By PO

#221 Fix fautes msg flash
  src/Controller/AdminOfferController.php
  src/Controller/AdminUserController.php
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/Controller/SecurityController.php
Labels: Reviewed By PO

#218 Fix company
  assets/css/appCompany.scss
  src/Entity/Offer.php
  src/Form/OfferType.php
  src/Migrations/Version20190110131313.php
  templates/Visitor/Offer/_form.html.twig
  templates/Visitor/Offer/new.html.twig
Labels: Changes Requested

#222 Alt ajouté
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/headerLogo.html.twig
Labels: Reviewed By PO

#224 Correction titre
  templates/Admin/associationIndex.html.twig
  templates/Admin/associationShow.html.twig
  templates/Admin/companyIndex.html.twig
  templates/Admin/companyShow.html.twig
  templates/Admin/foodHeroIndex.html.twig
  templates/Admin/index.html.twig
  templates/Admin/offerIndex.html.twig
  templates/Admin/offerShow.html.twig
  templates/Admin/userIndex.html.twig
Labels: Reviewed By PO

#227 Oui
  assets/images/favicon.png
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/index.html.twig
  templates/Visitor/Offer/indexForAssociation.html.twig
  templates/Visitor/Offer/new.html.twig
  templates/Visitor/Offer/showForAssociation.html.twig
  templates/base.html.twig
Labels: Reviewed By PO

#226 titre foodHero
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/show.html.twig
Labels: Reviewed By PO

#225 ajout modal info
  assets/css/app.scss
  assets/css/appFoodHero.scss
  src/Controller/FoodHeroController.php
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#230 ajout bouton fermer modal
  templates/Visitor/FoodHero/showMapOffer.html.twig
Labels: Reviewed By PO

#229 Dev
  assets/css/app.scss
  assets/css/appAssociation.scss
  assets/css/appCompany.scss
  assets/css/appFoodHero.scss
  assets/images/favicon.png
  src/Controller/AdminOfferController.php
  src/Controller/AdminUserController.php
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Controller/FoodHeroController.php
  src/Controller/OfferController.php
  src/Controller/SecurityController.php
  src/Entity/Offer.php
  src/Form/OfferType.php
  src/Migrations/Version20190110131313.php
  templates/Admin/associationIndex.html.twig
  templates/Admin/associationShow.html.twig
  templates/Admin/companyIndex.html.twig
  templates/Admin/companyShow.html.twig
  templates/Admin/foodHeroIndex.html.twig
  templates/Admin/index.html.twig
  templates/Admin/offerIndex.html.twig
  templates/Admin/offerShow.html.twig
  templates/Admin/userIndex.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/showCard.html.twig
  templates/Visitor/Company/edit.html.twig
  templates/Visitor/Company/editSchedule.html.twig
  templates/Visitor/Company/listOffers.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/Company/showCard.html.twig
  templates/Visitor/Company/showStatistics.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/show.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/FoodHero/showOffer.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/Visitor/Offer/edit.html.twig
  templates/Visitor/Offer/index.html.twig
  templates/Visitor/Offer/indexForAssociation.html.twig
  templates/Visitor/Offer/new.html.twig
  templates/Visitor/Offer/showForAssociation.html.twig
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/headerLogo.html.twig
Labels: Reviewed By PO

#231 Fix taille message flash
  assets/css/app.scss
Labels: Reviewed By PO

#232 bouton geoloc
  assets/js/geolocation.js
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/base.html.twig
Labels: Corrections Done, Reviewed By PO

#233 Rajout boutton quitter company
  templates/Visitor/Company/show.html.twig
Labels: Reviewed By PO

#234 Correction bug ajout user company
  templates/Visitor/Association/dropdownAssociationChoice.html.twig
  templates/Visitor/Company/dropdownCompanyChoice.html.twig
Labels: Reviewed By PO

#235 Fix taille message flash
  assets/css/app.scss
Labels: Reviewed By PO

#236 retour des modal et bouton identique
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
Labels: Corrections Done, Reviewed By PO

#237 fa text
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/FoodHero/new.html.twig
Labels: Reviewed By PO

#238 uniformisation
  templates/Visitor/Association/show.html.twig
Labels: Reviewed By PO

#239 w3c-check
  src/Form/OfferType.php
  src/Service/DistanceCalculator.php
  templates/Admin/index.html.twig
  templates/Admin/layoutAdmin.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
Labels: Corrections Done, Reviewed By PO

#240 Fix Images
  src/Entity/FoodHero.php
  src/Form/FoodHeroType.php
Labels: Reviewed By PO

#241 modif du bouton actif/inactif
  assets/css/appAdmin.scss
  templates/Admin/userIndex.html.twig
Labels: Reviewed By PO

#242 voters
  src/Controller/CompanyController.php
  src/Security/Voter/CompanyVoter.php
Labels: Reviewed By PO

#243 modif du bouton toggle des offres
  templates/Admin/offerShow.html.twig
Labels: Reviewed By PO

#244 modif du cadre pour modal et modif boutons FH
  templates/Visitor/Company/record.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
Labels: Reviewed By PO

#245 Dev
  assets/css/app.scss
  assets/css/appAdmin.scss
  assets/js/geolocation.js
  src/Controller/CompanyController.php
  src/Entity/FoodHero.php
  src/Form/FoodHeroType.php
  src/Form/OfferType.php
  src/Security/Voter/CompanyVoter.php
  src/Service/DistanceCalculator.php
  templates/Admin/index.html.twig
  templates/Admin/layoutAdmin.html.twig
  templates/Admin/offerShow.html.twig
  templates/Admin/userIndex.html.twig
  templates/Visitor/Association/dropdownAssociationChoice.html.twig
  templates/Visitor/Association/new.html.twig
  templates/Visitor/Association/record.html.twig
  templates/Visitor/Association/show.html.twig
  templates/Visitor/Company/dropdownCompanyChoice.html.twig
  templates/Visitor/Company/new.html.twig
  templates/Visitor/Company/record.html.twig
  templates/Visitor/Company/show.html.twig
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/listOffers.html.twig
  templates/Visitor/FoodHero/listOffersAccepted.html.twig
  templates/Visitor/FoodHero/new.html.twig
  templates/Visitor/FoodHero/record.html.twig
  templates/Visitor/FoodHero/showMapOffer.html.twig
  templates/Visitor/Offer/_form.html.twig
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
Labels: Reviewed By PO

#246 Guisharko patch 1 1
  README.md
Labels: Reviewed By PO

#248 Fix orthographe
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Entity/Offer.php
  templates/Visitor/Association/new.html.twig
Labels: Reviewed By PO

#250 Fix image
  src/Form/FoodHeroType.php
  src/Form/OfferType.php
Labels: Reviewed By PO

#254 Fix logo logout
  assets/css/app.scss
  templates/headerLogo.html.twig
Labels: Reviewed By PO

#255 Fix admin asso
  templates/Visitor/Association/show.html.twig
Labels: Reviewed By PO

#260 mise en page Edit et new de food hero
  templates/Visitor/FoodHero/edit.html.twig
  templates/Visitor/FoodHero/new.html.twig
Labels: Reviewed By PO

#261 change itirenary depending on geolocalization authorized or not
  templates/Visitor/FoodHero/showMapOffer.html.twig
Labels: Reviewed By PO

#263 Correction bug adresses invalides
  src/Controller/AssociationController.php
  src/Controller/CompanyController.php
  src/Service/AddressChecker.php
Labels: Corrections Done, Reviewed By PO

#264 Minifix
  templates/Visitor/Association/new.html.twig
Labels: Reviewed By PO

#265 Dev
  templates/Visitor/Association/new.html.twig
Labels: Reviewed By PO
